<template>
    <v-chip
        v-if="visible"
        class="ma-2"
        small
        close
        :color="color"
        text-color="white"
        close-icon="mdi-close"
        @click:close="visible=false"
    >
      <v-avatar left>
        <v-icon>{{icon}}</v-icon>
      </v-avatar>
      {{text}}
    </v-chip>
</template>
<script>
export default {
data(){
    return{
        visible:true
    }
},
props:{
    color:{
        type:String,
        default:"teal"
    },
    icon:{
        type:String,
        default:"mdi-checkbox-marked-circle"
    },
    text:{
        type:String,
        default:"Confirmed"
    }
}

}
</script>